/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnalyticsStatus = { 'error' : string } |
  { 'disconnected' : null } |
  { 'connected' : null };
export interface Campaign {
  'id' : string,
  'status' : CampaignStatus,
  'content' : CampaignContent,
  'scheduledStart' : [] | [bigint],
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'updatedAt' : bigint,
  'performance' : [] | [CampaignPerformanceMetrics],
  'scheduledEnd' : [] | [bigint],
  'budget' : bigint,
  'utmParameters' : {
    'source' : string,
    'campaign' : string,
    'medium' : string,
  },
  'industry' : IndustryCategory,
}
export interface CampaignContent {
  'headline' : string,
  'targetAudience' : string,
  'imageUrl' : string,
  'ctaText' : string,
  'bodyText' : string,
}
export interface CampaignMetrics {
  'signups' : bigint,
  'jobListingClicks' : bigint,
  'conversionRate' : number,
  'recommendationsViewed' : bigint,
  'interviewStarts' : bigint,
}
export interface CampaignPerformanceMetrics {
  'ctr' : number,
  'roi' : number,
  'clicks' : bigint,
  'impressions' : bigint,
  'spend' : bigint,
  'conversions' : bigint,
}
export type CampaignStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'draft' : null } |
  { 'paused' : null };
export interface CampaignTemplate {
  'id' : string,
  'headline' : string,
  'name' : string,
  'targetAudience' : string,
  'keywords' : Array<string>,
  'ctaText' : string,
  'bodyText' : string,
  'toneGuidelines' : string,
  'industry' : IndustryCategory,
}
export interface CareerRecommendation {
  'title' : string,
  'skillsGaps' : Array<string>,
  'description' : string,
  'image' : string,
  'guidance' : string,
}
export type ExternalBlob = Uint8Array;
export type FeedbackType = { 'compliment' : string } |
  { 'complaint' : string };
export type IndustryCategory = { 'skilledTrades' : null } |
  { 'healthcare' : null } |
  { 'environmentalAgriculture' : null } |
  { 'creative' : null } |
  { 'technology' : null } |
  { 'marineOutdoor' : null } |
  { 'businessFinance' : null };
export interface InterviewResponse { 'question' : string, 'answer' : string }
export interface JobListing {
  'title' : string,
  'description' : string,
  'company' : string,
  'skillGap' : [] | [SkillGapAnalysis],
  'careerContext' : [] | [CareerRecommendation],
  'requiredSkills' : Array<string>,
  'location' : string,
}
export interface JobPreference {
  'preferredSalary' : bigint,
  'jobType' : string,
  'location' : string,
}
export interface MarketingPlatformConfig {
  'status' : AnalyticsStatus,
  'trackingId' : string,
}
export interface PaymentCancelResponse {
  'message' : string,
  'sessionId' : string,
}
export type PaymentMethod = { 'stripeCheckout' : null };
export interface PaymentRecord {
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'timestamp' : bigint,
  'amount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'confirmed' : null } |
  { 'failed' : string };
export interface PaymentSuccessResponse {
  'message' : string,
  'payment' : {
    'status' : string,
    'paymentMethod' : { 'last4' : string, 'brand' : string },
    'currency' : string,
    'amount' : bigint,
  },
}
export interface PurchaseNotification {
  'paymentMethod' : PaymentMethod,
  'userId' : Principal,
  'subscriptionType' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface RecommendationStats {
  'timesRecommended' : bigint,
  'successStories' : bigint,
}
export interface SkillGapAnalysis {
  'recommendedSteps' : Array<string>,
  'jobTitle' : string,
  'missingSkills' : Array<string>,
}
export type StripeKeyMode = { 'live' : null } |
  { 'test' : null };
export interface StripeVerificationStatus {
  'mode' : [] | [StripeKeyMode],
  'errorMessage' : [] | [string],
  'lastVerified' : bigint,
  'isValid' : boolean,
}
export interface SubscriptionRecord {
  'status' : SubscriptionStatus,
  'paymentMethod' : PaymentMethod,
  'endDate' : bigint,
  'priceId' : string,
  'payment' : PaymentRecord,
  'startDate' : bigint,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'expired' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TwilioConfig {
  'accountSid' : Uint8Array,
  'adminPhoneNumber' : string,
  'authToken' : Uint8Array,
  'createdAt' : bigint,
  'lastVerified' : [] | [bigint],
  'updatedAt' : bigint,
  'verificationStatus' : [] | [TwilioVerificationStatus],
}
export interface TwilioVerificationStatus {
  'errorMessage' : [] | [string],
  'lastVerified' : bigint,
  'isValid' : boolean,
}
export interface UserFeedback {
  'feedbackType' : FeedbackType,
  'message' : string,
}
export interface UserProfile {
  'education' : string,
  'workHistory' : string,
  'careerGoals' : string,
  'skills' : Array<string>,
  'hobbies' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adaptJobListingsToCareerContext' : ActorMethod<
    [Array<JobListing>, CareerRecommendation],
    Array<JobListing>
  >,
  'analyzeCampaignPerformance' : ActorMethod<[CampaignMetrics], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelSubscription' : ActorMethod<[], undefined>,
  'createCampaign' : ActorMethod<
    [string, IndustryCategory, CampaignContent, bigint, string, string, string],
    string
  >,
  'createCampaignFromTemplate' : ActorMethod<
    [string, string, bigint, string, string, string],
    string
  >,
  'createCampaignTemplate' : ActorMethod<[CampaignTemplate], undefined>,
  'deleteCampaign' : ActorMethod<[string], undefined>,
  'duplicateCampaign' : ActorMethod<[string, string], string>,
  'fetchBlob' : ActorMethod<[string], Uint8Array>,
  'fetchExternalBlob' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'fetchExternalJobListings' : ActorMethod<[string], string>,
  'generateCampaignPreview' : ActorMethod<
    [string],
    [] | [
      {
        'headline' : string,
        'imageUrl' : string,
        'ctaText' : string,
        'bodyText' : string,
        'utmUrl' : string,
      }
    ]
  >,
  'generateCareerRecommendations' : ActorMethod<
    [UserProfile],
    Array<CareerRecommendation>
  >,
  'getAllCampaignTemplates' : ActorMethod<[], Array<CampaignTemplate>>,
  'getAllCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getAllConversionEvents' : ActorMethod<[], Array<[Principal, Array<string>]>>,
  'getAllFeedbacks' : ActorMethod<[], Array<UserFeedback>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCaller' : ActorMethod<[], Principal>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaign' : ActorMethod<[string], [] | [Campaign]>,
  'getCampaignMetrics' : ActorMethod<[], [] | [CampaignMetrics]>,
  'getCampaignPerformance' : ActorMethod<
    [string],
    [] | [CampaignPerformanceMetrics]
  >,
  'getCampaignTemplate' : ActorMethod<[string], [] | [CampaignTemplate]>,
  'getCampaignTemplatesByIndustry' : ActorMethod<
    [IndustryCategory],
    Array<CampaignTemplate>
  >,
  'getCampaignsByIndustry' : ActorMethod<[IndustryCategory], Array<Campaign>>,
  'getCampaignsByStatus' : ActorMethod<[CampaignStatus], Array<Campaign>>,
  'getCareerRecommendations' : ActorMethod<[], Array<CareerRecommendation>>,
  'getConversionEventHistory' : ActorMethod<[], Array<string>>,
  'getFeedbackByUser' : ActorMethod<[Principal], Array<UserFeedback>>,
  'getInterviewResponses' : ActorMethod<[], Array<InterviewResponse>>,
  'getJobListings' : ActorMethod<[], Array<JobListing>>,
  'getJobListingsByCareerContext' : ActorMethod<[string], Array<JobListing>>,
  'getJobPreferences' : ActorMethod<[], [] | [JobPreference]>,
  'getMarketingPlatformConfigs' : ActorMethod<
    [],
    [] | [Array<[string, MarketingPlatformConfig]>]
  >,
  'getPaymentStatus' : ActorMethod<[], PaymentStatus>,
  'getPaymentStatusForUser' : ActorMethod<[Principal], PaymentStatus>,
  'getPurchaseNotificationHistory' : ActorMethod<
    [],
    Array<PurchaseNotification>
  >,
  'getPurchaseNotificationsEnabled' : ActorMethod<[], boolean>,
  'getRecommendationStats' : ActorMethod<[string], [] | [RecommendationStats]>,
  'getSkillGapAnalysis' : ActorMethod<[], Array<SkillGapAnalysis>>,
  'getSortedCareerRecommendations' : ActorMethod<
    [Principal],
    Array<CareerRecommendation>
  >,
  'getStripeVerificationHistory' : ActorMethod<
    [],
    Array<StripeVerificationStatus>
  >,
  'getStripeVerificationStatus' : ActorMethod<
    [],
    [] | [StripeVerificationStatus]
  >,
  'getSubscription' : ActorMethod<[], [] | [SubscriptionRecord]>,
  'getSubscriptionForUser' : ActorMethod<
    [Principal],
    [] | [SubscriptionRecord]
  >,
  'getTwilioConfig' : ActorMethod<[], [] | [TwilioConfig]>,
  'getTwilioVerificationStatus' : ActorMethod<
    [],
    [] | [TwilioVerificationStatus]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasJobListingsWithCareerContext' : ActorMethod<[Principal, string], boolean>,
  'initializeStripePrices' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'manualVerifyStripeKeys' : ActorMethod<[], StripeVerificationStatus>,
  'manualVerifyTwilioConfig' : ActorMethod<[], TwilioVerificationStatus>,
  'paymentCancel' : ActorMethod<[string], PaymentCancelResponse>,
  'paymentSuccess' : ActorMethod<
    [string, string, string],
    PaymentSuccessResponse
  >,
  'retrieveBlob' : ActorMethod<[], Uint8Array>,
  'retryPayment' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCampaignMetrics' : ActorMethod<[CampaignMetrics], undefined>,
  'saveCareerRecommendations' : ActorMethod<
    [Array<CareerRecommendation>],
    undefined
  >,
  'saveInterviewResponses' : ActorMethod<[Array<InterviewResponse>], undefined>,
  'saveJobListings' : ActorMethod<[Array<JobListing>], undefined>,
  'saveJobPreferences' : ActorMethod<[JobPreference], undefined>,
  'saveMarketingPlatformConfig' : ActorMethod<
    [string, string, AnalyticsStatus],
    undefined
  >,
  'saveRecommendationStats' : ActorMethod<
    [string, RecommendationStats],
    undefined
  >,
  'saveSkillGapAnalysis' : ActorMethod<[Array<SkillGapAnalysis>], undefined>,
  'saveTwilioConfig' : ActorMethod<[Uint8Array, Uint8Array, string], undefined>,
  'saveUserFeedback' : ActorMethod<[UserFeedback], undefined>,
  'scheduleCampaign' : ActorMethod<[string, bigint, bigint], undefined>,
  'sendTestSms' : ActorMethod<[string], TwilioVerificationStatus>,
  'setPurchaseNotificationsEnabled' : ActorMethod<[boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCampaign' : ActorMethod<
    [string, string, CampaignContent, bigint],
    undefined
  >,
  'updateCampaignMetrics' : ActorMethod<[CampaignMetrics], undefined>,
  'updateCampaignPerformance' : ActorMethod<
    [string, CampaignPerformanceMetrics],
    undefined
  >,
  'updateCampaignStatus' : ActorMethod<[string, CampaignStatus], undefined>,
  'uploadExternalBlob' : ActorMethod<[ExternalBlob], undefined>,
  'validatePlatformInstallation' : ActorMethod<
    [string, string],
    AnalyticsStatus
  >,
  'verifyStripeKeys' : ActorMethod<[], StripeVerificationStatus>,
  'verifyTwilioConfig' : ActorMethod<[], TwilioVerificationStatus>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];