/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SkillGapAnalysis = IDL.Record({
  'recommendedSteps' : IDL.Vec(IDL.Text),
  'jobTitle' : IDL.Text,
  'missingSkills' : IDL.Vec(IDL.Text),
});
export const CareerRecommendation = IDL.Record({
  'title' : IDL.Text,
  'skillsGaps' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'image' : IDL.Text,
  'guidance' : IDL.Text,
});
export const JobListing = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'skillGap' : IDL.Opt(SkillGapAnalysis),
  'careerContext' : IDL.Opt(CareerRecommendation),
  'requiredSkills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const CampaignMetrics = IDL.Record({
  'signups' : IDL.Nat,
  'jobListingClicks' : IDL.Nat,
  'conversionRate' : IDL.Float64,
  'recommendationsViewed' : IDL.Nat,
  'interviewStarts' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const IndustryCategory = IDL.Variant({
  'skilledTrades' : IDL.Null,
  'healthcare' : IDL.Null,
  'environmentalAgriculture' : IDL.Null,
  'creative' : IDL.Null,
  'technology' : IDL.Null,
  'marineOutdoor' : IDL.Null,
  'businessFinance' : IDL.Null,
});
export const CampaignContent = IDL.Record({
  'headline' : IDL.Text,
  'targetAudience' : IDL.Text,
  'imageUrl' : IDL.Text,
  'ctaText' : IDL.Text,
  'bodyText' : IDL.Text,
});
export const CampaignTemplate = IDL.Record({
  'id' : IDL.Text,
  'headline' : IDL.Text,
  'name' : IDL.Text,
  'targetAudience' : IDL.Text,
  'keywords' : IDL.Vec(IDL.Text),
  'ctaText' : IDL.Text,
  'bodyText' : IDL.Text,
  'toneGuidelines' : IDL.Text,
  'industry' : IndustryCategory,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'education' : IDL.Text,
  'workHistory' : IDL.Text,
  'careerGoals' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'hobbies' : IDL.Vec(IDL.Text),
});
export const CampaignStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'draft' : IDL.Null,
  'paused' : IDL.Null,
});
export const CampaignPerformanceMetrics = IDL.Record({
  'ctr' : IDL.Float64,
  'roi' : IDL.Float64,
  'clicks' : IDL.Nat,
  'impressions' : IDL.Nat,
  'spend' : IDL.Nat,
  'conversions' : IDL.Nat,
});
export const Campaign = IDL.Record({
  'id' : IDL.Text,
  'status' : CampaignStatus,
  'content' : CampaignContent,
  'scheduledStart' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : IDL.Nat,
  'createdBy' : IDL.Principal,
  'updatedAt' : IDL.Nat,
  'performance' : IDL.Opt(CampaignPerformanceMetrics),
  'scheduledEnd' : IDL.Opt(IDL.Nat),
  'budget' : IDL.Nat,
  'utmParameters' : IDL.Record({
    'source' : IDL.Text,
    'campaign' : IDL.Text,
    'medium' : IDL.Text,
  }),
  'industry' : IndustryCategory,
});
export const FeedbackType = IDL.Variant({
  'compliment' : IDL.Text,
  'complaint' : IDL.Text,
});
export const UserFeedback = IDL.Record({
  'feedbackType' : FeedbackType,
  'message' : IDL.Text,
});
export const InterviewResponse = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const JobPreference = IDL.Record({
  'preferredSalary' : IDL.Nat,
  'jobType' : IDL.Text,
  'location' : IDL.Text,
});
export const AnalyticsStatus = IDL.Variant({
  'error' : IDL.Text,
  'disconnected' : IDL.Null,
  'connected' : IDL.Null,
});
export const MarketingPlatformConfig = IDL.Record({
  'status' : AnalyticsStatus,
  'trackingId' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
  'failed' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({ 'stripeCheckout' : IDL.Null });
export const PurchaseNotification = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'userId' : IDL.Principal,
  'subscriptionType' : IDL.Text,
  'timestamp' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const RecommendationStats = IDL.Record({
  'timesRecommended' : IDL.Nat,
  'successStories' : IDL.Nat,
});
export const StripeKeyMode = IDL.Variant({
  'live' : IDL.Null,
  'test' : IDL.Null,
});
export const StripeVerificationStatus = IDL.Record({
  'mode' : IDL.Opt(StripeKeyMode),
  'errorMessage' : IDL.Opt(IDL.Text),
  'lastVerified' : IDL.Nat,
  'isValid' : IDL.Bool,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'timestamp' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const SubscriptionRecord = IDL.Record({
  'status' : SubscriptionStatus,
  'paymentMethod' : PaymentMethod,
  'endDate' : IDL.Nat,
  'priceId' : IDL.Text,
  'payment' : PaymentRecord,
  'startDate' : IDL.Nat,
});
export const TwilioVerificationStatus = IDL.Record({
  'errorMessage' : IDL.Opt(IDL.Text),
  'lastVerified' : IDL.Nat,
  'isValid' : IDL.Bool,
});
export const TwilioConfig = IDL.Record({
  'accountSid' : IDL.Vec(IDL.Nat8),
  'adminPhoneNumber' : IDL.Text,
  'authToken' : IDL.Vec(IDL.Nat8),
  'createdAt' : IDL.Nat,
  'lastVerified' : IDL.Opt(IDL.Nat),
  'updatedAt' : IDL.Nat,
  'verificationStatus' : IDL.Opt(TwilioVerificationStatus),
});
export const PaymentCancelResponse = IDL.Record({
  'message' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const PaymentSuccessResponse = IDL.Record({
  'message' : IDL.Text,
  'payment' : IDL.Record({
    'status' : IDL.Text,
    'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  }),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adaptJobListingsToCareerContext' : IDL.Func(
      [IDL.Vec(JobListing), CareerRecommendation],
      [IDL.Vec(JobListing)],
      [],
    ),
  'analyzeCampaignPerformance' : IDL.Func([CampaignMetrics], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelSubscription' : IDL.Func([], [], []),
  'createCampaign' : IDL.Func(
      [
        IDL.Text,
        IndustryCategory,
        CampaignContent,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'createCampaignFromTemplate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCampaignTemplate' : IDL.Func([CampaignTemplate], [], []),
  'deleteCampaign' : IDL.Func([IDL.Text], [], []),
  'duplicateCampaign' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'fetchBlob' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat8)], ['query']),
  'fetchExternalBlob' : IDL.Func([ExternalBlob], [ExternalBlob], ['query']),
  'fetchExternalJobListings' : IDL.Func([IDL.Text], [IDL.Text], []),
  'generateCampaignPreview' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'headline' : IDL.Text,
            'imageUrl' : IDL.Text,
            'ctaText' : IDL.Text,
            'bodyText' : IDL.Text,
            'utmUrl' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'generateCareerRecommendations' : IDL.Func(
      [UserProfile],
      [IDL.Vec(CareerRecommendation)],
      [],
    ),
  'getAllCampaignTemplates' : IDL.Func(
      [],
      [IDL.Vec(CampaignTemplate)],
      ['query'],
    ),
  'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getAllConversionEvents' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'getAllFeedbacks' : IDL.Func([], [IDL.Vec(UserFeedback)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCaller' : IDL.Func([], [IDL.Principal], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaign' : IDL.Func([IDL.Text], [IDL.Opt(Campaign)], ['query']),
  'getCampaignMetrics' : IDL.Func([], [IDL.Opt(CampaignMetrics)], ['query']),
  'getCampaignPerformance' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CampaignPerformanceMetrics)],
      ['query'],
    ),
  'getCampaignTemplate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CampaignTemplate)],
      ['query'],
    ),
  'getCampaignTemplatesByIndustry' : IDL.Func(
      [IndustryCategory],
      [IDL.Vec(CampaignTemplate)],
      ['query'],
    ),
  'getCampaignsByIndustry' : IDL.Func(
      [IndustryCategory],
      [IDL.Vec(Campaign)],
      ['query'],
    ),
  'getCampaignsByStatus' : IDL.Func(
      [CampaignStatus],
      [IDL.Vec(Campaign)],
      ['query'],
    ),
  'getCareerRecommendations' : IDL.Func(
      [],
      [IDL.Vec(CareerRecommendation)],
      ['query'],
    ),
  'getConversionEventHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFeedbackByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(UserFeedback)],
      ['query'],
    ),
  'getInterviewResponses' : IDL.Func(
      [],
      [IDL.Vec(InterviewResponse)],
      ['query'],
    ),
  'getJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getJobListingsByCareerContext' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'getJobPreferences' : IDL.Func([], [IDL.Opt(JobPreference)], ['query']),
  'getMarketingPlatformConfigs' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, MarketingPlatformConfig)))],
      ['query'],
    ),
  'getPaymentStatus' : IDL.Func([], [PaymentStatus], ['query']),
  'getPaymentStatusForUser' : IDL.Func(
      [IDL.Principal],
      [PaymentStatus],
      ['query'],
    ),
  'getPurchaseNotificationHistory' : IDL.Func(
      [],
      [IDL.Vec(PurchaseNotification)],
      ['query'],
    ),
  'getPurchaseNotificationsEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getRecommendationStats' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RecommendationStats)],
      ['query'],
    ),
  'getSkillGapAnalysis' : IDL.Func([], [IDL.Vec(SkillGapAnalysis)], ['query']),
  'getSortedCareerRecommendations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CareerRecommendation)],
      ['query'],
    ),
  'getStripeVerificationHistory' : IDL.Func(
      [],
      [IDL.Vec(StripeVerificationStatus)],
      ['query'],
    ),
  'getStripeVerificationStatus' : IDL.Func(
      [],
      [IDL.Opt(StripeVerificationStatus)],
      ['query'],
    ),
  'getSubscription' : IDL.Func([], [IDL.Opt(SubscriptionRecord)], ['query']),
  'getSubscriptionForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SubscriptionRecord)],
      ['query'],
    ),
  'getTwilioConfig' : IDL.Func([], [IDL.Opt(TwilioConfig)], ['query']),
  'getTwilioVerificationStatus' : IDL.Func(
      [],
      [IDL.Opt(TwilioVerificationStatus)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasJobListingsWithCareerContext' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'initializeStripePrices' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'manualVerifyStripeKeys' : IDL.Func([], [StripeVerificationStatus], []),
  'manualVerifyTwilioConfig' : IDL.Func([], [TwilioVerificationStatus], []),
  'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
  'paymentSuccess' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [PaymentSuccessResponse],
      [],
    ),
  'retrieveBlob' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
  'retryPayment' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCampaignMetrics' : IDL.Func([CampaignMetrics], [], []),
  'saveCareerRecommendations' : IDL.Func(
      [IDL.Vec(CareerRecommendation)],
      [],
      [],
    ),
  'saveInterviewResponses' : IDL.Func([IDL.Vec(InterviewResponse)], [], []),
  'saveJobListings' : IDL.Func([IDL.Vec(JobListing)], [], []),
  'saveJobPreferences' : IDL.Func([JobPreference], [], []),
  'saveMarketingPlatformConfig' : IDL.Func(
      [IDL.Text, IDL.Text, AnalyticsStatus],
      [],
      [],
    ),
  'saveRecommendationStats' : IDL.Func([IDL.Text, RecommendationStats], [], []),
  'saveSkillGapAnalysis' : IDL.Func([IDL.Vec(SkillGapAnalysis)], [], []),
  'saveTwilioConfig' : IDL.Func(
      [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8), IDL.Text],
      [],
      [],
    ),
  'saveUserFeedback' : IDL.Func([UserFeedback], [], []),
  'scheduleCampaign' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'sendTestSms' : IDL.Func([IDL.Text], [TwilioVerificationStatus], []),
  'setPurchaseNotificationsEnabled' : IDL.Func([IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCampaign' : IDL.Func(
      [IDL.Text, IDL.Text, CampaignContent, IDL.Nat],
      [],
      [],
    ),
  'updateCampaignMetrics' : IDL.Func([CampaignMetrics], [], []),
  'updateCampaignPerformance' : IDL.Func(
      [IDL.Text, CampaignPerformanceMetrics],
      [],
      [],
    ),
  'updateCampaignStatus' : IDL.Func([IDL.Text, CampaignStatus], [], []),
  'uploadExternalBlob' : IDL.Func([ExternalBlob], [], []),
  'validatePlatformInstallation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [AnalyticsStatus],
      [],
    ),
  'verifyStripeKeys' : IDL.Func([], [StripeVerificationStatus], []),
  'verifyTwilioConfig' : IDL.Func([], [TwilioVerificationStatus], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SkillGapAnalysis = IDL.Record({
    'recommendedSteps' : IDL.Vec(IDL.Text),
    'jobTitle' : IDL.Text,
    'missingSkills' : IDL.Vec(IDL.Text),
  });
  const CareerRecommendation = IDL.Record({
    'title' : IDL.Text,
    'skillsGaps' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'image' : IDL.Text,
    'guidance' : IDL.Text,
  });
  const JobListing = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'skillGap' : IDL.Opt(SkillGapAnalysis),
    'careerContext' : IDL.Opt(CareerRecommendation),
    'requiredSkills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const CampaignMetrics = IDL.Record({
    'signups' : IDL.Nat,
    'jobListingClicks' : IDL.Nat,
    'conversionRate' : IDL.Float64,
    'recommendationsViewed' : IDL.Nat,
    'interviewStarts' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const IndustryCategory = IDL.Variant({
    'skilledTrades' : IDL.Null,
    'healthcare' : IDL.Null,
    'environmentalAgriculture' : IDL.Null,
    'creative' : IDL.Null,
    'technology' : IDL.Null,
    'marineOutdoor' : IDL.Null,
    'businessFinance' : IDL.Null,
  });
  const CampaignContent = IDL.Record({
    'headline' : IDL.Text,
    'targetAudience' : IDL.Text,
    'imageUrl' : IDL.Text,
    'ctaText' : IDL.Text,
    'bodyText' : IDL.Text,
  });
  const CampaignTemplate = IDL.Record({
    'id' : IDL.Text,
    'headline' : IDL.Text,
    'name' : IDL.Text,
    'targetAudience' : IDL.Text,
    'keywords' : IDL.Vec(IDL.Text),
    'ctaText' : IDL.Text,
    'bodyText' : IDL.Text,
    'toneGuidelines' : IDL.Text,
    'industry' : IndustryCategory,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'education' : IDL.Text,
    'workHistory' : IDL.Text,
    'careerGoals' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'hobbies' : IDL.Vec(IDL.Text),
  });
  const CampaignStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'draft' : IDL.Null,
    'paused' : IDL.Null,
  });
  const CampaignPerformanceMetrics = IDL.Record({
    'ctr' : IDL.Float64,
    'roi' : IDL.Float64,
    'clicks' : IDL.Nat,
    'impressions' : IDL.Nat,
    'spend' : IDL.Nat,
    'conversions' : IDL.Nat,
  });
  const Campaign = IDL.Record({
    'id' : IDL.Text,
    'status' : CampaignStatus,
    'content' : CampaignContent,
    'scheduledStart' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : IDL.Nat,
    'createdBy' : IDL.Principal,
    'updatedAt' : IDL.Nat,
    'performance' : IDL.Opt(CampaignPerformanceMetrics),
    'scheduledEnd' : IDL.Opt(IDL.Nat),
    'budget' : IDL.Nat,
    'utmParameters' : IDL.Record({
      'source' : IDL.Text,
      'campaign' : IDL.Text,
      'medium' : IDL.Text,
    }),
    'industry' : IndustryCategory,
  });
  const FeedbackType = IDL.Variant({
    'compliment' : IDL.Text,
    'complaint' : IDL.Text,
  });
  const UserFeedback = IDL.Record({
    'feedbackType' : FeedbackType,
    'message' : IDL.Text,
  });
  const InterviewResponse = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
  });
  const JobPreference = IDL.Record({
    'preferredSalary' : IDL.Nat,
    'jobType' : IDL.Text,
    'location' : IDL.Text,
  });
  const AnalyticsStatus = IDL.Variant({
    'error' : IDL.Text,
    'disconnected' : IDL.Null,
    'connected' : IDL.Null,
  });
  const MarketingPlatformConfig = IDL.Record({
    'status' : AnalyticsStatus,
    'trackingId' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
    'failed' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({ 'stripeCheckout' : IDL.Null });
  const PurchaseNotification = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'userId' : IDL.Principal,
    'subscriptionType' : IDL.Text,
    'timestamp' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const RecommendationStats = IDL.Record({
    'timesRecommended' : IDL.Nat,
    'successStories' : IDL.Nat,
  });
  const StripeKeyMode = IDL.Variant({ 'live' : IDL.Null, 'test' : IDL.Null });
  const StripeVerificationStatus = IDL.Record({
    'mode' : IDL.Opt(StripeKeyMode),
    'errorMessage' : IDL.Opt(IDL.Text),
    'lastVerified' : IDL.Nat,
    'isValid' : IDL.Bool,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'status' : PaymentStatus,
    'method' : PaymentMethod,
    'timestamp' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const SubscriptionRecord = IDL.Record({
    'status' : SubscriptionStatus,
    'paymentMethod' : PaymentMethod,
    'endDate' : IDL.Nat,
    'priceId' : IDL.Text,
    'payment' : PaymentRecord,
    'startDate' : IDL.Nat,
  });
  const TwilioVerificationStatus = IDL.Record({
    'errorMessage' : IDL.Opt(IDL.Text),
    'lastVerified' : IDL.Nat,
    'isValid' : IDL.Bool,
  });
  const TwilioConfig = IDL.Record({
    'accountSid' : IDL.Vec(IDL.Nat8),
    'adminPhoneNumber' : IDL.Text,
    'authToken' : IDL.Vec(IDL.Nat8),
    'createdAt' : IDL.Nat,
    'lastVerified' : IDL.Opt(IDL.Nat),
    'updatedAt' : IDL.Nat,
    'verificationStatus' : IDL.Opt(TwilioVerificationStatus),
  });
  const PaymentCancelResponse = IDL.Record({
    'message' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const PaymentSuccessResponse = IDL.Record({
    'message' : IDL.Text,
    'payment' : IDL.Record({
      'status' : IDL.Text,
      'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
      'currency' : IDL.Text,
      'amount' : IDL.Nat,
    }),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adaptJobListingsToCareerContext' : IDL.Func(
        [IDL.Vec(JobListing), CareerRecommendation],
        [IDL.Vec(JobListing)],
        [],
      ),
    'analyzeCampaignPerformance' : IDL.Func([CampaignMetrics], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelSubscription' : IDL.Func([], [], []),
    'createCampaign' : IDL.Func(
        [
          IDL.Text,
          IndustryCategory,
          CampaignContent,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'createCampaignFromTemplate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCampaignTemplate' : IDL.Func([CampaignTemplate], [], []),
    'deleteCampaign' : IDL.Func([IDL.Text], [], []),
    'duplicateCampaign' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'fetchBlob' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat8)], ['query']),
    'fetchExternalBlob' : IDL.Func([ExternalBlob], [ExternalBlob], ['query']),
    'fetchExternalJobListings' : IDL.Func([IDL.Text], [IDL.Text], []),
    'generateCampaignPreview' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'headline' : IDL.Text,
              'imageUrl' : IDL.Text,
              'ctaText' : IDL.Text,
              'bodyText' : IDL.Text,
              'utmUrl' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'generateCareerRecommendations' : IDL.Func(
        [UserProfile],
        [IDL.Vec(CareerRecommendation)],
        [],
      ),
    'getAllCampaignTemplates' : IDL.Func(
        [],
        [IDL.Vec(CampaignTemplate)],
        ['query'],
      ),
    'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getAllConversionEvents' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'getAllFeedbacks' : IDL.Func([], [IDL.Vec(UserFeedback)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCaller' : IDL.Func([], [IDL.Principal], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaign' : IDL.Func([IDL.Text], [IDL.Opt(Campaign)], ['query']),
    'getCampaignMetrics' : IDL.Func([], [IDL.Opt(CampaignMetrics)], ['query']),
    'getCampaignPerformance' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CampaignPerformanceMetrics)],
        ['query'],
      ),
    'getCampaignTemplate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CampaignTemplate)],
        ['query'],
      ),
    'getCampaignTemplatesByIndustry' : IDL.Func(
        [IndustryCategory],
        [IDL.Vec(CampaignTemplate)],
        ['query'],
      ),
    'getCampaignsByIndustry' : IDL.Func(
        [IndustryCategory],
        [IDL.Vec(Campaign)],
        ['query'],
      ),
    'getCampaignsByStatus' : IDL.Func(
        [CampaignStatus],
        [IDL.Vec(Campaign)],
        ['query'],
      ),
    'getCareerRecommendations' : IDL.Func(
        [],
        [IDL.Vec(CareerRecommendation)],
        ['query'],
      ),
    'getConversionEventHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFeedbackByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(UserFeedback)],
        ['query'],
      ),
    'getInterviewResponses' : IDL.Func(
        [],
        [IDL.Vec(InterviewResponse)],
        ['query'],
      ),
    'getJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getJobListingsByCareerContext' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getJobPreferences' : IDL.Func([], [IDL.Opt(JobPreference)], ['query']),
    'getMarketingPlatformConfigs' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, MarketingPlatformConfig)))],
        ['query'],
      ),
    'getPaymentStatus' : IDL.Func([], [PaymentStatus], ['query']),
    'getPaymentStatusForUser' : IDL.Func(
        [IDL.Principal],
        [PaymentStatus],
        ['query'],
      ),
    'getPurchaseNotificationHistory' : IDL.Func(
        [],
        [IDL.Vec(PurchaseNotification)],
        ['query'],
      ),
    'getPurchaseNotificationsEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getRecommendationStats' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RecommendationStats)],
        ['query'],
      ),
    'getSkillGapAnalysis' : IDL.Func(
        [],
        [IDL.Vec(SkillGapAnalysis)],
        ['query'],
      ),
    'getSortedCareerRecommendations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CareerRecommendation)],
        ['query'],
      ),
    'getStripeVerificationHistory' : IDL.Func(
        [],
        [IDL.Vec(StripeVerificationStatus)],
        ['query'],
      ),
    'getStripeVerificationStatus' : IDL.Func(
        [],
        [IDL.Opt(StripeVerificationStatus)],
        ['query'],
      ),
    'getSubscription' : IDL.Func([], [IDL.Opt(SubscriptionRecord)], ['query']),
    'getSubscriptionForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SubscriptionRecord)],
        ['query'],
      ),
    'getTwilioConfig' : IDL.Func([], [IDL.Opt(TwilioConfig)], ['query']),
    'getTwilioVerificationStatus' : IDL.Func(
        [],
        [IDL.Opt(TwilioVerificationStatus)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasJobListingsWithCareerContext' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'initializeStripePrices' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'manualVerifyStripeKeys' : IDL.Func([], [StripeVerificationStatus], []),
    'manualVerifyTwilioConfig' : IDL.Func([], [TwilioVerificationStatus], []),
    'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
    'paymentSuccess' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PaymentSuccessResponse],
        [],
      ),
    'retrieveBlob' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
    'retryPayment' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCampaignMetrics' : IDL.Func([CampaignMetrics], [], []),
    'saveCareerRecommendations' : IDL.Func(
        [IDL.Vec(CareerRecommendation)],
        [],
        [],
      ),
    'saveInterviewResponses' : IDL.Func([IDL.Vec(InterviewResponse)], [], []),
    'saveJobListings' : IDL.Func([IDL.Vec(JobListing)], [], []),
    'saveJobPreferences' : IDL.Func([JobPreference], [], []),
    'saveMarketingPlatformConfig' : IDL.Func(
        [IDL.Text, IDL.Text, AnalyticsStatus],
        [],
        [],
      ),
    'saveRecommendationStats' : IDL.Func(
        [IDL.Text, RecommendationStats],
        [],
        [],
      ),
    'saveSkillGapAnalysis' : IDL.Func([IDL.Vec(SkillGapAnalysis)], [], []),
    'saveTwilioConfig' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8), IDL.Text],
        [],
        [],
      ),
    'saveUserFeedback' : IDL.Func([UserFeedback], [], []),
    'scheduleCampaign' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'sendTestSms' : IDL.Func([IDL.Text], [TwilioVerificationStatus], []),
    'setPurchaseNotificationsEnabled' : IDL.Func([IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCampaign' : IDL.Func(
        [IDL.Text, IDL.Text, CampaignContent, IDL.Nat],
        [],
        [],
      ),
    'updateCampaignMetrics' : IDL.Func([CampaignMetrics], [], []),
    'updateCampaignPerformance' : IDL.Func(
        [IDL.Text, CampaignPerformanceMetrics],
        [],
        [],
      ),
    'updateCampaignStatus' : IDL.Func([IDL.Text, CampaignStatus], [], []),
    'uploadExternalBlob' : IDL.Func([ExternalBlob], [], []),
    'validatePlatformInstallation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [AnalyticsStatus],
        [],
      ),
    'verifyStripeKeys' : IDL.Func([], [StripeVerificationStatus], []),
    'verifyTwilioConfig' : IDL.Func([], [TwilioVerificationStatus], []),
  });
};

export const init = ({ IDL }) => { return []; };